http:
 port: "8081"
 
sfdc:
 username: "contact.heartbook@gov.et"
 password: "Ethio2014@ET"
 token: "9F0nSF8DLoNIUThvnc0O4cJ5p"
 
file:
 accountsDir: "/Users/melak/Desktop/APDevFundamentals4.4_studentFiles_SP_06may2022/resources"
  
db:
 host: "mudb.learn.mulesoft.com"
 port: "3306"
 user: "mule"
 password: "mule"
 database: "training"